module.exports = mock_course = [
    {
        title: "Développement",
        short_description: "Le deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
        description: "He es o his eneaaion",
        outcomes: "{'Devenir dev','Programmer un pro'}",
        requirements:"{'Algorithmique','Prise en charge'}",
        language_id:1,
        category_id:1,
        price:250,
        discounted_price:50,
        level:"Intermédiaire",
        user_id:5,
        thumbnail:"images/01.png",
        video_url:"ouuunn/njjjjjhhh?8577",
        visibility:1,
        is_top_course:1,
        is_admin:1,
        status:"Payé",
        course_overview_provider:"Youtube",
        is_free_course:1,
    },
    {
        title: "Infographie",
        short_description: "Le deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
        description: "He es o his eneaaion",
        outcomes: "{'Devenir dev','Programmer un pro'}",
        requirements:"{'Algorithmique','Prise en charge'}",
        language_id:1,
        category_id:1,
        price:250,
        discounted_price:50,
        level:"Intermédiaire",
        user_id: 6,
        thumbnail:"images/01.png",
        video_url:"ouuunn/njjjjjhhh?8577",
        visibility:1,
        is_top_course:1,
        is_admin:1,
        status:"Payé",
        course_overview_provider:"Youtube",
        is_free_course:1,
    }
]